---
# Setup DNS records
- hosts: localhost
  environment:
    GCP_AUTH_KIND: "serviceaccount"
    GCP_SERVICE_ACCOUNT_FILE: "{{ gcp_service_account_file }}"
    GCP_SCOPES: "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
  tasks:
    - name: Create DNS zone
      gcp_dns_managed_zone:
        name: "humblenlp"
        dns_name: "humblenlp.com."
        description: "Humble NLP"
        project: "{{ gcp_project }}"
        state: "present"
        visibility: "public"
    - name: Create DNS record
      gcp_dns_resource_record_set:
        managed_zone:
          name: "humblenlp"
          dnsName: "humblenlp.com."
        project: "{{ gcp_project }}"
        state: "present"
        ttl: 3600
        type: "A"
        name: "humblenlp.com."
        target:
          - 34.72.70.43
    - name: Create DNS record
      gcp_dns_resource_record_set:
        managed_zone:
          name: "humblenlp"
          dnsName: "humblenlp.com."
        project: "{{ gcp_project }}"
        state: "present"
        ttl: 3600
        type: "A"
        name: "*.humblenlp.com."
        target:
          - 34.72.70.43
    - name: Create DNS record
      gcp_dns_resource_record_set:
        managed_zone:
          name: "humblenlp"
          dnsName: "humblenlp.com."
        project: "{{ gcp_project }}"
        state: "present"
        ttl: 3600
        type: "A"
        name: "www.humblenlp.com."
        target:
          - 34.72.70.43
    - name: Create DNS record
      gcp_dns_resource_record_set:
        managed_zone:
          name: "humblenlp"
          dnsName: "humblenlp.com."
        project: "{{ gcp_project }}"
        state: "present"
        ttl: 3600
        type: "MX"
        name: "humblenlp.com."
        target:
          - "{{ item }}"
      loop:
        - 1 ASPMX.L.GOOGLE.COM.
        - 5 ALT1.ASPMX.L.GOOGLE.COM.
        - 5 ALT2.ASPMX.L.GOOGLE.COM.
        - 10 ALT3.ASPMX.L.GOOGLE.COM.
        - 10 ALT4.ASPMX.L.GOOGLE.COM.