---
# Setup GCP with compute instance
- hosts: localhost
  tags: global
  tasks:
    # Add firewall rules for http
    - name: "Create http firewall rule"
      gce_net:
        name: default
        fwname: "default-allow-http"
        allowed: "tcp:80"
        state: "present"
        src_range: "0.0.0.0/0"
        project_id: "{{ gcp_project }}"
        target_tags: "http-server"
        credentials_file: "{{ gcp_service_account_file }}"
        service_account_email: "{{ gcp_service_account_email }}"
    # Add firewall rules for https
    - name: "Create https firewall rule"
      gce_net:
        name: default
        fwname: "default-allow-https"
        allowed: "tcp:443"
        state: "present"
        src_range: "0.0.0.0/0"
        project_id: "{{ gcp_project }}"
        target_tags: "http-server"
        credentials_file: "{{ gcp_service_account_file }}"
        service_account_email: "{{ gcp_service_account_email }}"
    # Create static IP address
    - name: Create static IP address
      connection: local
      gcp_compute_address:
        auth_kind: "serviceaccount"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "https://www.googleapis.com/auth/compute"
        address_type: "EXTERNAL"
        name: "{{ machine_instance_name }}"
        network_tier: "PREMIUM"
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        state: present
      register: address
    # Create Persistent Disk
    - name: Create Compute disk
      gcp_compute_disk:
        auth_kind: "serviceaccount"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "https://www.googleapis.com/auth/compute"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        name: "{{ persistent_disk_name }}"
        size_gb: "{{ persistent_disk_size }}"
        state: "present"
      register: disk
    # Create Compute Instance
    - name: Create Compute Instance
      gcp_compute_instance:
        auth_kind: "serviceaccount"
        service_account_file: "{{ gcp_service_account_file }}"
        scopes: "https://www.googleapis.com/auth/compute"
        name: "{{ machine_instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/debian-cloud/global/images/family/debian-10"
              disk_size_gb: "{{ machine_disk_size }}"
          - auto_delete: false
            boot: false
            source: "{{ disk }}"
        network_interfaces:
          - access_configs:
            - name: "External NAT"
              type: "ONE_TO_ONE_NAT"
              nat_ip: "{{ address }}"
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        state: present
      register: instance
    - name: Wait for SSH to come up
      wait_for: host={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} port=22 delay=10 timeout=120
    - name: Add host to groupname
      add_host: hostname={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} groupname=new_instances