- name: Configure containers on app server
  hosts: appserver
  connection: ssh
  become: true

  tasks:
    - name: Copy docker tag file
      copy:
        src: ~/.docker-tag
        dest: ~/.docker-tag
        mode: 0644
    - name: "Get docker tag"
      shell: "cat ~/.docker-tag"
      register: tag
    - name: Print tag
      debug:
        var: tag
    - name: Create frontend container
      docker_container:
        name: "annotations-frontend"
        image: "gcr.io/{{ gcp_project }}/annotations-frontend:{{ tag.stdout}}"
        state: started
        recreate: yes
        pull: yes
        restart: yes
        published_ports:
          - 3000:80
        networks:
          - name: "{{docker_network_name}}"

    # Create a folder on persistent disk for db data
    - name: Create data directory
      file:
        path: "/mnt/disk-1/data"
        state: "directory"
        mode: 0777
    - name: Create model store directory
      file:
        path: "/mnt/disk-1/model-store"
        state: "directory"
        mode: 0777

    # Create Postgress DB container
    - name: Create postgres container
      docker_container:
        name: "postgres"
        image: "postgres:latest"
        state: started
        recreate: yes
        published_ports:
          - 5432:5432
        env:
          POSTGRES_USER: "hlexg"
          POSTGRES_PASSWORD: "annotate"
          POSTGRES_DB: "hlexgdb"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/data:/var/lib/postgresql/data # Data folder in persistent drive
  
    - name: Copy db migration scripts
      copy:
        src: "../../database-server/db"
        dest: "/conf"

    - name: Run DB migrations using dbmate
      shell: docker run --rm -it -v /conf/db:/db -e DATABASE_URL=postgres://hlexg:annotate@postgres/hlexgdb?sslmode=disable --network "{{docker_network_name}}" amacneil/dbmate up

    - name: Create api-service container
      docker_container:
        name: "api-service"
        image: "gcr.io/{{ gcp_project }}/api-service:{{ tag.stdout}}"
        state: started
        recreate: yes
        published_ports:
          - 9000:9000
        env:
          DATABASE_URL: "postgres://hlexg:annotate@postgres/hlexgdb"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/model-store:/modelstore
  
    - name: Check if containers are running
      shell: docker ps